### PR TITLE
add overlapwithones

### PR DESCRIPTION
**Pull request by TysonRayJones**
which calculates the overlap of a PauliSum (or PauliString) with an arbitrary computational basis state, specified by the indices (indexing from 1) of its one-bits.

This interface (specifying individual bit indices) was chosen over something like `overlapwithbasisstate(index)` (specifying the global state index) to avoid the miserable issues of one-indexing

### CODE REVIEW

**Comment by MSRudolph** [comment]
Seems very cool!

**Review by MSRudolph — APPROVED** [review]

**Comment by teng10** [comment]
Nicely documented :)

I understand the confusion with global integer index but what about `overlapwithbits`? I think `overlapwithones` makes me think `|11...1>`....

Btw with this function, we can redefine :)
`overlapwithzero(pstr) = overlapwithones(pstr, [])`

> I did not perform any user-input validation of input (i.e. elements are unique, positive integers) because I'm unsure where we're validating, and I see a lot of other existing functions ([e.g.](https://github.com/MSRudolph/PauliPropagation.jl/blob/c958292e86f412d0bbb5e6965908128221b755f4/src/circuits.jl#L152)) which do not validate. What are our plans for validation?

It's been on my long running todo list to add comprehensive unit tests.
And I think we should add tests as we develop.. so I just added some in `test_overlaps.jl`. Feel free to add additional tests for edge cases!

**Review by teng10 — APPROVED** [review]

**Comment by TysonRayJones** [comment]
Renaming inner, and outer to `overlapwithcomputational`

**Comment by MSRudolph** [comment]
Nice!

**Pull request merged**
